
#!/bin/bash

# Configuration
USER_HESTIA="quiulacocha"
DOMAIN="quiulacocha.theworkpc.com"
APP_DIR="/home/$USER_HESTIA/web/$DOMAIN/public_html" # Changing to public_html as it always exists and has permissions.
REPO_URL="https://github.com/Start-Games/asistencia-quiulaocha.git" # Replace with actual repo if different, assuming public or keys setup.
BRANCH="main" # or master

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}Starting Deployment for $DOMAIN...${NC}"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run as root (sudo su) to ensure Docker and permissions work correctly.${NC}"
  echo "Try: sudo ./deploy_server.sh"
  exit 1
fi

# 1. Prepare Directory & Permissions
if [ ! -d "$APP_DIR" ]; then
    echo "Creating directory $APP_DIR..."
    mkdir -p "$APP_DIR"
fi

# Ensure specific ownership before starting (safe measure)
chown -R $USER_HESTIA:$USER_HESTIA "$APP_DIR"

cd "$APP_DIR"

# 2. Pull Changes (as user quiulacocha to avoid root-owned git files)
if [ -d ".git" ]; then
    echo "Pulling latest changes..."
    sudo -u $USER_HESTIA git pull origin $BRANCH
else
    echo "Cloning repository..."
    # Clone as user quiulacocha
    sudo -u $USER_HESTIA git clone $REPO_URL .
fi

# 3. Check .env
if [ ! -f ".env" ]; then
    echo -e "${RED}WARNING: .env file not found!${NC}"
    echo "Creating a default .env file..."
    cp .env.example .env 2>/dev/null || touch .env
    
    # Pre-populate defaults
    grep -q "POSTGRES_DB" .env || echo "POSTGRES_DB=asistencia_db" >> .env
    grep -q "POSTGRES_USER" .env || echo "POSTGRES_USER=usuario_db" >> .env
    grep -q "POSTGRES_PASSWORD" .env || echo "POSTGRES_PASSWORD=change_me_please" >> .env
    grep -q "POSTGRES_HOST" .env || echo "POSTGRES_HOST=db" >> .env
    grep -q "POSTGRES_PORT" .env || echo "POSTGRES_PORT=5432" >> .env
    grep -q "ALLOWED_HOSTS" .env || echo "ALLOWED_HOSTS=$DOMAIN,localhost,127.0.0.1" >> .env
    grep -q "CSRF_TRUSTED_ORIGINS" .env || echo "CSRF_TRUSTED_ORIGINS=https://$DOMAIN" >> .env
    grep -q "DEBUG" .env || echo "DEBUG=False" >> .env
    grep -q "SECRET_KEY" .env || echo "SECRET_KEY=change_me_super_secret_$(date +%s)" >> .env

    # Fix ownership of generated .env
    chown $USER_HESTIA:$USER_HESTIA .env
fi

# 4. Build and Run Docker (Docker runs as root usually)
echo "Building and starting containers for production..."
docker compose -f docker-compose.yml up -d --build

# 5. Run Migrations & Collect Static
echo "Running migrations..."
docker compose exec web python manage.py migrate

echo "Collecting static files..."
docker compose exec web python manage.py collectstatic --noinput

# 6. Final Permission Fix
echo "Fixing ownership for Hestia CP..."
# Ensure everything in public_html is owned by the user, especially static files generated by docker
chown -R $USER_HESTIA:$USER_HESTIA "$APP_DIR"

# 7. Install Nginx Templates (Automatic)
if [ -d "nginx_hestia_templates" ]; then
    echo "Installing Hestia Nginx templates..."
    cp nginx_hestia_templates/django-8000.tpl /usr/local/hestia/data/templates/web/nginx/
    cp nginx_hestia_templates/django-8000.stpl /usr/local/hestia/data/templates/web/nginx/
    echo "Templates installed to /usr/local/hestia/data/templates/web/nginx/"
fi

# 8. Check Status
if [ $? -eq 0 ]; then
    echo -e "${GREEN}Deployment Finished Successfully!${NC}"
    echo "App reachable at http://127.0.0.1:8000 locally."
    echo "Ensure your Hestia Proxy Template is set to 'django-8000' or points to port 8000."
else
    echo -e "${RED}Deployment Failed! Check logs with: docker compose logs -f${NC}"
fi
