"""
Django settings for qr_asistencia project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib.util
import mimetypes
import os
from pathlib import Path

from qr_asistencia.env import get_bool, get_csv, get_first, load_environment, resolve_path

mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/javascript", ".js", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_environment()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool("DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY and not DEBUG:
    raise Exception("SECRET_KEY must be set explicitly in the environment.")
elif not SECRET_KEY:
    SECRET_KEY = "django-insecure-dev-only-change-me"

default_allowed_hosts = "*" if DEBUG else "localhost,127.0.0.1"
ALLOWED_HOSTS = get_csv("ALLOWED_HOSTS", default_allowed_hosts)
ALLOWED_HOSTS.extend(get_csv("EXTRA_ALLOWED_HOSTS", ""))
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

# CSRF Trusted Origins
default_csrf_origins = (
    "http://localhost,http://127.0.0.1,"
    "http://localhost:8000,http://127.0.0.1:8000,"
    "http://localhost:8001,http://127.0.0.1:8001,"
    "https://quiulacocha.theworkpc.com"
)
CSRF_TRUSTED_ORIGINS = list(
    dict.fromkeys(get_csv("CSRF_TRUSTED_ORIGINS", default_csrf_origins))
)

# Configuracion para Proxy Inverso (Nginx/HestiaCP)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "asistencia",
    "rest_framework",
    "rest_framework.authtoken",
    "widget_tweaks",
    "axes",  # Proteccion contra fuerza bruta
]
if importlib.util.find_spec("jazzmin") is not None:
    INSTALLED_APPS.insert(0, "jazzmin")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",  # Debe ir despues de AuthenticationMiddleware
]

ROOT_URLCONF = "qr_asistencia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "asistencia.context_processors.sistema_config",
            ],
        },
    },
]

WSGI_APPLICATION = "qr_asistencia.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

POSTGRES_DB = get_first("POSTGRES_DB", "DB_NAME")
POSTGRES_USER = get_first("POSTGRES_USER", "DB_USER")
POSTGRES_PASSWORD = get_first("POSTGRES_PASSWORD", "DB_PASSWORD")
POSTGRES_HOST = get_first("POSTGRES_HOST", "DB_HOST")
POSTGRES_PORT = get_first("POSTGRES_PORT", "DB_PORT")

if all([POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST, POSTGRES_PORT]):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": str(POSTGRES_DB),
            "USER": str(POSTGRES_USER),
            "PASSWORD": str(POSTGRES_PASSWORD),
            "HOST": str(POSTGRES_HOST),
            "PORT": str(POSTGRES_PORT),
            "CONN_MAX_AGE": 60,
        }
    }
else:
    sqlite_name = get_first("SQLITE_NAME", "SQLITE_PATH", default="db.sqlite3")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(resolve_path(sqlite_name, base_dir=BASE_DIR)),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-pe"

TIME_ZONE = "America/Lima"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get("STATIC_URL", "/static/")
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STATIC_ROOT = resolve_path(get_first("STATIC_ROOT", default="staticfiles"), base_dir=BASE_DIR)

MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")
MEDIA_ROOT = resolve_path(get_first("MEDIA_ROOT", default="media"), base_dir=BASE_DIR)
SERVE_MEDIA_FILES = get_bool("SERVE_MEDIA_FILES", True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configuracion de sesiones
SESSION_COOKIE_AGE = 43200  # 12 horas
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = get_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = get_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_SSL_REDIRECT = get_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CSRF_COOKIE_HTTPONLY = True

# Seguridad adicional para produccion
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Security Hardening
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "UNAUTHENTICATED_USER": None,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
}

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/perfil/"

JAZZMIN_SETTINGS = {
    "site_title": "QR Asistencia Admin",
    "site_header": "QR Asistencia",
    "site_brand": "QR Asistencia",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Bienvenido al panel de administracion de QR Asistencia",
    "copyright": "QR Asistencia Ltd",
    "search_model": ["asistencia.Usuario"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Sitio", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "asistencia.Usuario": "fas fa-user-friends",
        "asistencia.Asistencia": "fas fa-clipboard-check",
        "asistencia.Ubicacion": "fas fa-map-marker-alt",
        "asistencia.Evento": "fas fa-calendar-alt",
        "asistencia.LogAccion": "fas fa-history",
        "asistencia.ConfiguracionSistema": "fas fa-cogs",
        "asistencia.Justificacion": "fas fa-file-medical",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-primary",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

# ============================================
# CONFIGURACION DE DJANGO-AXES (Seguridad Login)
# ============================================

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = None
AXES_VERBOSE = True
AXES_ENABLE_ADMIN = True
# Axes 6.1.1 intenta escribir en AccessLog sin session_hash en este entorno.
# Desactivamos solo ese access log para evitar el 500 en login y mantener el bloqueo por intentos fallidos.
AXES_DISABLE_ACCESS_LOG = True
