# Generated by Django 5.2 on 2025-05-05 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil_fotos/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_manage_users', 'Can manage users'), ('can_scan_qr', 'Can scan QR codes')],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.evento')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LogAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha'], name='asistencia__fecha_bb2bf2_idx'), models.Index(fields=['usuario'], name='asistencia__usuario_ee2dcc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['dni'], name='asistencia__dni_a92db6_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha'], name='asistencia__fecha_c5c62b_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['usuario'], name='asistencia__usuario_58140f_idx'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['evento'], name='asistencia__evento__45a64e_idx'),
        ),
    ]
