# Generated by Django 5.2 on 2026-01-30 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_usuario_estado_usuario_fecha_nacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='es_justificada',
            field=models.BooleanField(default=False, help_text='Indica si la inasistencia fue justificada'),
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo de la inasistencia')),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='justificaciones/', verbose_name='Evidencia (Foto/Documento)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobada'), ('RECHAZADO', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario_admin', models.TextField(blank=True, help_text='Comentario opcional del administrador', verbose_name='Comentario del Admin')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='asistencia.evento')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_procesadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='asistencia.usuario')),
            ],
        ),
    ]
