# Generated by Django 5.2 on 2026-01-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_asistencia_es_justificada_justificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='nombre_institucion',
            field=models.CharField(default='QUIULACOCHA', help_text='Nombre de la institución (se mostrará en toda la aplicación)', max_length=100),
        ),
    ]
