# Generated by Django 5.2 on 2026-02-02 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_create_scanner_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='tolerancia_minutos',
            field=models.PositiveIntegerField(default=15, help_text='Tiempo de tolerancia en minutos para el ingreso antes de considerarse tardanza (si aplica)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_ingreso',
            field=models.TimeField(default='08:00', help_text='Hora de ingreso programada'),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='justificaciones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Evidencia (Foto/Documento)'),
        ),
    ]
