# Generated by Django 6.0.2 on 2026-02-26 08:01

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencia", "0007_configuracionsistema_tolerancia_minutos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asistencia",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="justificacion",
            name="evidencia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="justificaciones/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Evidencia (Foto/Documento)",
            ),
        ),
    ]
