# Generated by Django 6.0.2 on 2026-04-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_asistencia_puntualidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='tardanza_activa',
            field=models.BooleanField(default=True, help_text='Activa el control de tardanzas para marcar faltas cuando se supera el límite.'),
        ),
    ]
