# Generated by Django 5.2 on 2026-04-09 06:14

import asistencia.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0011_configuracionsistema_tardanza_activa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo del sistema (se mostrará en la barra de navegación, login y reportes)', null=True, upload_to='logos/', validators=[asistencia.models.validate_file_size, asistencia.models.validate_image_content]),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='justificaciones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), asistencia.models.validate_file_size, asistencia.models.validate_supporting_document_content], verbose_name='Evidencia (Foto/Documento)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/', validators=[asistencia.models.validate_file_size, asistencia.models.validate_image_content]),
        ),
        migrations.CreateModel(
            name='HistorialCarnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('Primer Carnet', 'Primer Carnet'), ('Renovación por Vencimiento', 'Renovación por Vencimiento'), ('Reposición por Pérdida/Robo', 'Reposición por Pérdida/Robo'), ('Reposición por Deterioro', 'Reposición por Deterioro')], max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo/Anulado', 'Inactivo/Anulado')], default='Activo', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_carnets', to='asistencia.usuario')),
            ],
        ),
    ]
