# Generated by Django 5.2 on 2026-04-09 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0012_alter_configuracionsistema_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcarnet',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
