# The order here is critical: require the helper FIRST
ruby_project_dir = File.dirname(File.realpath(__FILE__))
require File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), ruby_project_dir)

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods ruby_project_dir
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
